server:
  port: 8090

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

service:
  person:
    url: http://localhost:8080
  allotment:
    url: http://localhost:8080
